[[redirects]]
  from = "/pathx"
  to = "https://reactive-giraffe-attempt2.herokuapp.com/patha"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"